server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leecx
    username: root
    password: JavaL0318.
  freemarker:
    # 设置 ftl 文件路径
    # 关闭缓存，及时刷新，上线环境需要改为 true
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .html
    template-loader-path: classpath:/templates
